name: Deploy to VPS

on:
  push:
    branches: ["main"]    # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # List local nginx/media files (debug)
      - name: List local nginx/media files
        run: ls -l ./nginx/media/

      # Ensure nginx/media folder exists on VPS
      - name: Create nginx/media folder on VPS
        run: |
         ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
           mkdir -p ${{ secrets.VPS_DEPLOY_PATH }}/nginx/media
           ls -l ${{ secrets.VPS_DEPLOY_PATH }}/nginx/media/
         "

      - name: Copy default.conf to VPS
        run: |
          scp ./nginx/media/default.conf ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEPLOY_PATH }}/nginx/media/default.conf

      - name: Copy project to VPS
        run: |
          rsync -avz \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "__pycache__" \
            ./ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEPLOY_PATH }}/

      - name: Build and restart services on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ${{ secrets.VPS_DEPLOY_PATH }} &&
            docker compose build --no-cache &&
            docker compose up -d
          "
