name: Deploy to VPS

on:
  push:
    branches: ["main"]    # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Copy project to VPS
        run: |
          rsync -avz \
            --exclude ".git" \
            --exclude "node_modules" \
            --exclude "__pycache__" \
            ./ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEPLOY_PATH }}/

      - name: Ensure nginx media config exists on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            mkdir -p ${{ secrets.VPS_DEPLOY_PATH }}/nginx/media
            CONFIG_FILE='${{ secrets.VPS_DEPLOY_PATH }}/nginx/media/default.conf'
            if [ ! -f \$CONFIG_FILE ]; then
              echo 'Creating default nginx/media/default.conf...'
              cat << 'EOF' > \$CONFIG_FILE
                server {
                    listen 80;
                    
                    location /static_django/ {
                    alias /static/;
                    access_log off;
                    expires 30d;
                }
                
                  location /media/ {
                  alias /media/;
                  access_log off;
                  expires 30d;
                }
                }
                EOF
            else
            echo 'nginx/media/default.conf already exists'
            fi
            ls -l ${{ secrets.VPS_DEPLOY_PATH }}/nginx/media/
            "

      - name: Build and restart services on VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ${{ secrets.VPS_DEPLOY_PATH }} &&
            docker compose build --no-cache &&
            docker compose up -d
          "
